spring.application.name=scm2.0

server.port=8081

#mysql database configurations


#data source url
spring.datasource.url=jdbc:mysql://localhost:3306/scm20
spring.datasource.username=root
spring.datasource.password=root1234

#jpa configurations(to see the queries of the sql)
spring.jpa.show-sql=true

#for creating schema and tables (to enable Spring to create schemas automatically)
spring.jpa.hibernate.ddl-auto=update
